name: umrah_guide
description: Panduan Umrah - Doa, Gambar dan Audio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.40
  flutter_html: ^3.0.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/doa/
    - assets/images/icons/
    - assets/images/overview/
    - assets/images/locations/
    - assets/images/misc/
    - assets/audio/
    - assets/text/
